# Generated by Django 3.1.5 on 2021-01-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('marked_data', models.CharField(max_length=2000)),
                ('text_data', models.CharField(max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('social_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=500)),
                ('join_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('methrics', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=500)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaul_main.data')),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('social_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaul_main.social')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaul_main.users')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaul_main.logins'),
        ),
    ]
